apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::574748894319:role/service-role/codebuild-Brain-tasks-app-service-role
      username: codebuild
      groups:
        - system:masters

