version: 0.2

env:
  variables:
    DOCKERHUB_USERNAME: "sathishdocker3011"
    DOCKERHUB_PASSWORD: "Admin@123"
    AWS_DEFAULT_REGION: "us-east-1"

phases:
  install:
    commands:
      - echo Installing kubectl...
      - ARCH=$(uname -m)
      - if [ "$ARCH" = "x86_64" ]; then ARCH=amd64; elif [ "$ARCH" = "aarch64" ]; then ARCH=arm64; fi
      - curl -LO "https://dl.k8s.io/release/$(curl -sL https://dl.k8s.io/release/stable.txt)/bin/linux/$ARCH/kubectl"
      - chmod +x kubectl
      - mv kubectl /usr/local/bin/
      - kubectl version --client
      - echo "Login to DockerHub..."
      - echo $DOCKERHUB_PASSWORD | docker login --username $DOCKERHUB_USERNAME --password-stdin
  build:
    commands:
      - echo "Build Docker image..."
      - docker build -t brain-tasks-app .
      - docker tag brain-tasks-app $DOCKERHUB_USERNAME/brain-tasks-app:latest
  post_build:
    commands:
      - echo "Push Docker image..."
      - docker push $DOCKERHUB_USERNAME/brain-tasks-app:latest
      - echo "Testing AWS credentials..."
      - aws sts get-caller-identity
      - echo "Update kubeconfig..."
      - aws eks update-kubeconfig --name brain-tasks-cluster --region us-east-1
      - echo "Verify connection to cluster..."
      - kubectl get nodes
      - echo "Deploy to EKS..."
      - kubectl apply -f deployment.yaml
      - kubectl apply -f service.yaml

artifacts:
  files: []
