version: 0.2

env:
  variables:
    DOCKERHUB_USERNAME: "sathishdocker3011"
    DOCKERHUB_PASSWORD: "Admin@123"
    AWS_DEFAULT_REGION: "us-east-1"

phases:
  pre_build:
    commands:
      - echo "Install kubectl..."
      - curl -LO curl -o kubectl https://amazon-eks.s3.us-east-1.amazonaws.com/1.29.0/2024-02-22/bin/linux/amd64/kubectl
      - chmod +x kubectl
      - mv kubectl /usr/local/bin/
      - echo "Login to DockerHub..."
      - echo $DOCKERHUB_PASSWORD | docker login --username $DOCKERHUB_USERNAME --password-stdin
  build:
    commands:
      - echo "Build Docker image..."
      - docker build -t brain-tasks-app .
      - docker tag brain-tasks-app $DOCKERHUB_USERNAME/brain-tasks-app:latest
  post_build:
    commands:
      - echo "Push Docker image..."
      - docker push $DOCKERHUB_USERNAME/brain-tasks-app:latest
      - echo "Update kubeconfig..."
      - aws eks update-kubeconfig --name brain-tasks-cluster --region $AWS_DEFAULT_REGION
      - echo "Verify connection to cluster..."
      - kubectl get nodes
      - echo "Deploy to EKS..."
      - kubectl apply -f deployment.yaml
      - kubectl apply -f service.yaml

artifacts:
  files: []

