version: 0.2

env:
  variables:
    DOCKERHUB_USERNAME: "sathishdocker3011"
    DOCKERHUB_PASSWORD: "Admin@123"
    AWS_DEFAULT_REGION: "us-east-1"

    version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin sathishdocker3011.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - docker build -t brain-tasks-app .
      - docker tag brain-tasks-app:latest sathishdocker3011.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/brain-tasks-app:latest
  post_build:
    commands:
      - echo Pushing image to ECR...
      - docker push sathishdocker3011.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/brain-tasks-app:latest
      - kubectl apply -f deployment.yaml
artifacts:
  files:
    - deployment.yaml
